 @@@ BEFORE @@@
 .....
 Instance->EfiFile.Revision    = EFI_FILE_PROTOCOL_REVISION2;
 Instance->EfiFile.Open        = FileOpen;
 ....
 @@@ AFTER @@@
  .....
 Instance->EfiFile.Revision    = EFI_FILE_PROTOCOL_REVISION;
 Instance->EfiFile.Open        = FileOpen;
 ....
